apiVersion : apps/v1
kind: Deployment
metadata:
  name: "sentimentclusterqa-906c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "sentimentclusterqa-906c"
  template:
    metadata:
      labels:
        app: "sentimentclusterqa-906c"
    spec:
      containers:
        - name: "sentimentclusterqa-906c"
          image: "containerregistryrsmylie.azurecr.io/sentimentclusterqa"
          ports:
          - containerPort: 8080